name: Renovate
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: {}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.11
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
